### ISSUE TITLE
Reporter Handler for generating kepler.gl inputs

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/hive#117]
a recent prototype script was created which takes event.log and state.log outputs and produces "trips" animation datasets which can be read in at [https://kepler.gl/](https://kepler.gl/). to make this a feature of core-hive, it should collect directly from internal reports as a new Reporting [Handler](https://github.com/NREL/hive/blob/main/nrel/hive/reporting/handler/handler.py) class.

the structure of these datasets should be:

```python
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": { 
        "vehicle_id": str,
        "vehicle_state": VehicleStateType,
        "start_time": int,
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [-74.20986, 40.81773, 0, 1564184363],
          [-74.20987, 40.81765, 0, 1564184396],
          [-74.20998, 40.81746, 0, 1564184409],
          ...
        ]
      }
    }
    ...
  ]
}
```

where each "coordinate" is a [lon, lat, z, timestamp] tuple.

each Feature should contain a complete trajectory for a Vehicle under a contiguous VehicleStateType. this will require buffering trajectories in the Reporter, which will increase the memory requirements of HIVE in a dynamic way. but this can be mitigated to some degree by writing completed trajectories to the log (in the correct GeoJSON format), and writing the header of the file as:

```json
{
  "type": "FeatureCollection",
  "features": [
```

#### configuration

- add log_kepler: False to the [default global hive config](https://github.com/NREL/hive/blob/main/nrel/hive/config/global_config.py)
- add this new handler to hive conditionally based on global_config.log_kepler [here](https://github.com/NREL/hive/blob/main/nrel/hive/initialization/initialize_simulation.py#L175)

#### future work

this assumes we are only writing positions of vehicles at the timestep, ignoring the details of each intra-step move, and allowing kepler.gl to interpolate them. a more ideal output would be to report each incremental intersection along the move trajectories, but for this, we would need to report the sub-timestep time at which each road network intersection is reached and collect those observations for kepler, which is future work.

**Comment by robfitzgerald** [comment]
the script created to generate simple kepler animations from hive outputs:

[2022-11-15-hive-to-kepler.ipynb.zip](https://github.com/NREL/hive/files/11153244/2022-11-15-hive-to-kepler.ipynb.zip)

**Comment by zenon18** [comment]
I would like to work on this

**Comment by robfitzgerald** [comment]
@zenon18 lemme check, one moment

**Comment by robfitzgerald** [comment]
@zenon18 that last bit ("station priorities") is unrelated to generating animations of vehicles from the outputs of a base hive scenario, so you can ignore it.

**Comment by zenon18** [comment]
got it thanks

**Comment by robfitzgerald** [comment]
just for fun, here's the output that the script generated. i think it's exactly what you should expect, because i didn't end up adding the "station priorities" data, so this is just vehicle trajectories by vehicle type.

https://user-images.githubusercontent.com/7003022/234049473-079bce65-3655-42a0-9c79-837228398a70.mov

**Comment by zenon18** [comment]
I have a couple of clarifying questions.

1. Would you want a separate json per VehicleStateType or a collection of types to take advantage of layering in kepler.gl?
   a. One possibility if you want by groups could be how you separated the types 0-2, 10-13 (*_TRIP), 20-22(*_BASE), 30-23
2. Are there any state types you don't want logged?
3. By completed trajectory do you mean when the vehicle changes from one state type to another state type, or can a vehicle state the same type and complete a trajectory?

**Comment by robfitzgerald** [comment]
@zenon18 sorry for the delay, i had a meeting

> Would you want a separate json per VehicleStateType or a collection of types to take advantage of layering in kepler.gl?

one JSON file across all vehicles. when you choose "trip" in kepler.gl, there's a way to color the animation by a field. that can be assigned to the "vehicle_state" property in the move events json file.

> Are there any state types you don't want logged?

this is a good question. i think my notebook was focusing on charging and charging dispatch, but really, i think it would be great to output all vehicle state types in the vehicles animations output file.

**Comment by zenon18** [comment]
got it thanks

**Comment by jhoshiko** [comment]
Closing this after PR #188
