### ISSUE TITLE
report energy used in summary

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/hive#126]
a high level stat we are missing is the overall energy use of each fleet, alongside `Total Kilometers Traveled`. would also be valuable in the time step stats. this can be achieved by updating the [stats](https://github.com/NREL/hive/blob/main/nrel/hive/reporting/handler/stats_handler.py) and [time step stats](https://github.com/NREL/hive/blob/main/nrel/hive/reporting/handler/time_step_stats_handler.py) handlers.

**Comment by nreinicke** [comment]
closed by #179
