### ISSUE TITLE
HIVE core written in lower-level language

### ISSUE THREAD

**Issue by robfitzgerald** [NREL/hive#13]
the core of HIVE is Python. we could improve on memory management and runtime if HIVE were written in C++ or another language which can interface with Python.

the rewrite should be limited to "SimulationState", "Environment", and below. the instructions should still come in Python, though, the logic for their "apply" methods should join the refactor. immutability should still be enforced, and, Vehicles should still be serializable. id types could be made into integers (if the hive executable creates enumeration tables to maintain a reference to the user-provided ids).

**Comment by nreinicke** [comment]
#118 opens the door to this by sampling the refactor for a single hive core object into Rust.

Before we continue down this road, though, it would be wise to do a "study" into how feasible a full core refactor would be by investigating:

 - how does Ray handle python libraries with compiled rust backend? (hive-distributed)
 - provide examples of CI/CD with python rust projects
 - are there stable rust libraries to support the required hive core dependencies? 
   - immutable data stores
   - linear interpolation
   - shortest path search
   - rtree
   - h3

**Comment by nreinicke** [comment]
Closing to be replaced by #158
