### ISSUE TITLE
Implement batch runner

### ISSUE THREAD

**Issue by nreinicke** [NREL/hive#14]
Certain users of the model have expressed a need for an easy way to run multiple simulations in parallel. One suggested solution was to use a bash script that the `hive` command multiple times using:

```
hive my-sim1.yaml &
hive my-sim2.yaml
```

but this method has been failing when used in conjunction with slurm. 

It would be helpful to have a new command (maybe `hive-batch`) that could load multiple simulations and execute them in parallel from a single overhead process.

**Comment by robfitzgerald** [comment]
Closed in #15
