### ISSUE TITLE
Experiment with pre-commit hooks to run black and ruff

### ISSUE THREAD

**Issue by jhoshiko** [NREL/hive#178]
It might be beneficial to run black automatically with a pre-commit hook to catch black errors.

**Comment by nreinicke** [comment]
I would advocate adding [ruff](https://github.com/charliermarsh/ruff) for our linting.

**Comment by nreinicke** [comment]
Based on running ruff over the current codebase, we're touching almost all the files and so we should postpone doing this until we have a lull in PRs

**Comment by machallboyd** [comment]
To clarify, black and ruff as precommits wouldn't just be catching errors, they would be fixing the errors for you

**Comment by machallboyd** [comment]
Doing some experiments with this in `pyproject.toml`

```[tool.black]
line-length = 100

[tool.ruff]
line-length = 100```

Obnoxiously, `black` seems to consider this line to be 92 characters long and thus safe.

```
                    [len(v.vehicle_state.trip_plan) for v in veh_dispatch_pooling_in_fleet]  # type: ignore
```

Ruff considers the line to include its inline comment `# type: ignore` to be part of it, and yells about it. Black ignores comments

```
nrel/hive/reporting/handler/time_step_stats_handler.py:321:101: E501 Line too long (107 > 100 characters)
```
