### ISSUE TITLE
Derive link speed from road network

### ISSUE THREAD

**Issue by nreinicke** [NREL/hive#26]
NOTE: this is dependent on the incorporation of https://github.com/NREL/hive/pull/19

When we move a vehicle we consume a previously generated link traversal object which has fixed speed and travel time information. In order to future proof this for inclusion of variable links speeds, we should probably get speed and travel time information from the road network at the time it's consumed.

**Comment by erik-hasse** [comment]
I'm going to give this one a try today

**Comment by erik-hasse** [comment]
I dug into this a bit and talked it over with @nreinicke. There are some logical inconsistencies between `Link` and `LinkTraversal` that make it harder to implement. So it makes sense to table this and either incorporate it into the Rust refactor or fix the Link inconsistencies if Rust doesn't work out
